### ISSUE TITLE
Problem with compilation on Windows 8 / 64bit

### ISSUE THREAD

**Issue by PunkSage** [idflood/ThreeNodes.js#44]
I am following the instructions regarding compilation:

npm install -d
grunt build

That result in error: 

C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.8.5/lib/bundler/resolver.rb:369:in `resolve': Could not find gem 'compass (= 1.0.0.alpha.19) x86-mingw32' in the gems available on this machine. (Bundler::GemNotFoun
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.8.5/lib/bundler/resolver.rb:167:in `start'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.8.5/lib/bundler/resolver.rb:129:in `resolve'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.8.5/lib/bundler/definition.rb:193:in `resolve'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.8.5/lib/bundler/definition.rb:132:in `specs'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.8.5/lib/bundler/definition.rb:177:in `specs_for'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.8.5/lib/bundler/definition.rb:166:in `requested_specs'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.8.5/lib/bundler/environment.rb:18:in `requested_specs'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.8.5/lib/bundler/runtime.rb:13:in `setup'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.8.5/lib/bundler.rb:122:in `setup'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.8.5/lib/bundler/setup.rb:18:in `<top (required)>'
        from c:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from c:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'

Any idea how to proceed from this point?

**Comment by yousifucv** [comment]
I'm getting the same errors

**Comment by PunkSage** [comment]
Do you have similar problem on Linux or MacOS?

**Comment by yousifucv** [comment]
I did not test it on other OS's other than Window 8.1 64bit
