### ISSUE TITLE
Issue with development setup on windows machine

### ISSUE THREAD

**Issue by hmandal** [idflood/ThreeNodes.js#47]
```
OS: Windows 7 Enterprise SP1
Architecture: 64-bit
Node: v8.1.2
npm: 5.0.3
ruby: 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]
python: 2.7.13
grunt-cli: v1.2.0
compass: 1.0.3 (Polaris)
```

I followed the steps mentioned in [Development Setup](https://github.com/idflood/ThreeNodes.js#development-setup) but I'm getting errors. 

The steps mentiond in the above link are incomplete. While installing `compass`, we first need to install `ruby`. Then upon `npm install -d`, the console throws some `node-gyp` errors. Even `grunt build` is not working, throws some `node-sass` errors (I tried `npm install -g node-sass` too).

I tried `npm install node-gyp -g` but then there are some other errors.

Here are some relevant console logs: (###: path hidden for privacy reasons)
<details>
  <summary>Log for: npm install -d (Click to expand)</summary>

```bash
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (###\AppData\Roaming\npm\nod
e_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:197:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "###\\AppData
\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "re
build"
gyp ERR! cwd ###\node_modules\weak
gyp ERR! node -v v8.1.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm info lifecycle weak@0.2.2~install: Failed to exec install script
npm WARN ThreeNodes.js@0.2.0 No license field.
npm WARN The package grunt-contrib-clean is included as both a dev and productio
n dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fse
vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! weak@0.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the weak@0.2.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ###\AppData\Roaming\npm-cache\_logs\2017-07-11T09_00_08_3
15Z-debug.log
```
</details>

<details>
  <summary>Log for: grunt build (Click to expand)</summary>

```bash
>> Local Npm module "grunt-contrib-requirejs" not found. Is it installed?
Loading "sass.js" tasks...ERROR
>> Error: Missing binding ###\node_modules\node-sass\vendor\
win32-x64-57\binding.node
>> Node Sass could not find a binding for your current environment: Windows 64-b
it with Node.js 8.x
>>
>> Found bindings for the following environments:
>>   - Windows 64-bit with Node.js 6.x
>>
>> This usually happens because your environment has changed since running `npm
install`.
>> Run `npm rebuild node-sass --force` to build the binding for your current env
ironment.
Warning: Task "sass" not found. Use --force to continue.

Aborted due to warnings.
```
</details>

It would be helpful if someone could provide concrete steps to install `ThreeNodes.js development setup` in the `Windows environment`.

Cc: @idflood

**Comment by but0n** [comment]
## Same problem!

![image](https://user-images.githubusercontent.com/7625588/37242256-35aecdbc-24a1-11e8-9c43-8969c6f46d3f.png)
